version: '2'
services:
  api:
    build: ./auth-api
    ports:
      - "5000:5000"
    volumes:
      - ./auth-api:/code
    depends_on:
      - redis
  redis:
    image: redis
  bot:
    build: ./discord-bot
    volumes:
      - ./discord-bot:/code
    depends_on:
      - api
